app = "dj-wishlist"

[build]
    image = "fehuworks/dj-wishlist:latest"

[env]
    PORT = "8080"

[[services]]
    internal_port = 8080
    protocol = "tpc"

    [[services.ports]]
        handlers = ["http"]
        port = 80